services:
  - type: web
    name: alpaca-trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook_server.py
    envVars:
      - key: ALPACA_API_KEY
        value: <你的API_KEY>
      - key: ALPACA_SECRET_KEY
        value: <你的SECRET_KEY>
      - key: ALPACA_BASE_URL
        value: https://paper-api.alpaca.markets
